In [2]:
import tensorflow as tf
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [3]:
tf.constant([[1,2,3],
            [4,5,6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [4]:
tf.constant([[[1,2,3],
            [4,5,6]],
            [[2,5,6],
            [5,7,9]]])

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 5, 6],
        [5, 7, 9]]])>

In [5]:
import numpy as np
array_1 = np.array([1,2,3])

In [6]:
converted_array = tf.convert_to_tensor(array_1)

In [7]:
converted_array

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [8]:
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns = None,
    batch_shape = [3,],
    dtype = tf.dtypes.float32,
    name=None
)

In [9]:
eye_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]], dtype=float32)>

In [10]:
Filled = tf.fill(dims = [3,5,4,6,3,4],value= 5)

In [11]:
Filled

<tf.Tensor: shape=(3, 5, 4, 6, 3, 4), dtype=int32, numpy=
array([[[[[[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]]],


         [[[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]],

          [[5, 5, 5, 5],
           [5, 5, 5, 5],
           [5, 5, 5, 5]]],


         [[[5,

In [12]:
t1 = [[[1,2,3],
       [4,5,6]]]
t2 = [[[7,8,9],
       [10,11,12]]]

print(f'T1_Shape: {tf.constant(t2).shape}')
print(f'T2_shape: {tf.constant(t1).shape}')

T1_Shape: (1, 2, 3)
T2_shape: (1, 2, 3)


In [13]:
tf.concat([t1, t2], axis = 0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [14]:
tf.concat([t1, t2], axis = 1)

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])>

In [15]:
tensor_sparse = tf.sparse.SparseTensor(
    indices = [[1,1], [3,4]], values = [11,56], dense_shape= [5,6] 
)

In [16]:
tensor_sparse

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [ ]:
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]])>

: 